### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by oliviassin** [asu-cis440-summer/career-center-jkswy#12]

**Comment by djoplin** [comment]
Tech Talk information

**Comment by djoplin** [comment]
search engine optimization

**Comment by oliviassin** [comment]
https://docs.google.com/a/asu.edu/presentation/d/10MV9LHLMKJ_9R-vTGT3qeodMbHD7H3MWy5eawJqoOoQ/edit?usp=sharing_eid

**Comment by djoplin** [comment]
Everyone make their own 10 slides to talk about during the presentation. having  around 50 total slides should be able to fill most of the class time. do not read right off the slide, try an explain deeper on what is already in text.
