### ISSUE TITLE
Footer - links

### ISSUE THREAD

**Issue by djoplin** [asu-cis440-summer/career-center-jkswy#32]

**Comment by djoplin** [comment]
need to talk to webspark people on how to edit this

**Comment by oliviassin** [comment]
information on updating a bit-
https://webspark.asu.edu/features/mega-footer

address:
W. P. Carey School of Business Career Center
PO Box 3406 - BA 180U
Arizona State University
Tempe, AZ 85287-3406

links to social media on their website- https://my.wpcarey.asu.edu/undergrad/bcc/bcc-overview.cfm
